#!/usr/bin/env bash
# Parses Setupfile and dispatches each line to the appropriate installer.
set -euo pipefail

SETUPFILE="${1:-Setupfile}"

if [[ ! -f "$SETUPFILE" ]]; then
  echo "Error: $SETUPFILE not found" >&2
  exit 1
fi

# Plugin URL lookup — add cases here to support new plugins
_plugin_url() {
  case "$1" in
    zsh-syntax-highlighting) echo "https://github.com/zsh-users/zsh-syntax-highlighting" ;;
    zsh-autosuggestions)     echo "https://github.com/zsh-users/zsh-autosuggestions" ;;
    zsh-completions)         echo "https://github.com/zsh-users/zsh-completions" ;;
    powerlevel10k)           echo "https://github.com/romkatv/powerlevel10k" ;;
    *)                       echo "" ;;
  esac
}

ZSH_PLUGINS_FILE="$HOME/.zsh_plugins.zsh"
# Start fresh each run so removed plugins don't linger
echo "# Auto-generated by install.sh — do not edit manually" > "$ZSH_PLUGINS_FILE"
echo "plugins=(" >> "$ZSH_PLUGINS_FILE"

_install_plugin() {
  local name="$1"
  local url
  url=$(_plugin_url "$name")

  if [[ -z "$url" ]]; then
    echo "Warning: unknown plugin '$name' — skipping (add it to _plugin_url in install.sh)" >&2
    return
  fi

  local dest="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/$name"
  if [[ ! -d "$dest" ]]; then
    git clone --depth=1 "$url" "$dest"
  else
    echo "Plugin '$name' already installed, skipping clone."
  fi

  echo "  $name" >> "$ZSH_PLUGINS_FILE"
}

while IFS= read -r line; do
  # Skip blank lines and comments
  [[ "$line" =~ ^[[:space:]]*(#|$) ]] && continue

  keyword=$(awk '{print $1}' <<< "$line")
  # Extract first double-quoted value; strip the quotes (grep exits 1 on no match — suppress with ||)
  value=$(grep -o '"[^"]*"' <<< "$line" | head -1 | tr -d '"' || true)

  case "$keyword" in
    name)
      echo "Configuring git user.name..."
      git config --global user.name "$value"
      ;;
    email)
      echo "Configuring git user.email..."
      git config --global user.email "$value"
      ;;
    gitignore)
      echo "Downloading .gitignore_global..."
      curl -sL "https://www.toptal.com/developers/gitignore/api/$value" -o "$HOME/.gitignore_global"
      git config --global core.excludesfile "$HOME/.gitignore_global"
      ;;
    plugin)
      echo "Installing plugin: $value"
      _install_plugin "$value"
      ;;
    brew)
      echo "brew install $value"
      brew install "$value"
      ;;
    cask)
      echo "brew install --cask $value"
      brew install --cask "$value"
      ;;
    pip)
      echo "pip install $value"
      python3 -m pip install --user "$value"
      ;;
    run)
      # 'run' lines have no quoted value — grab everything after the keyword
      cmd=$(sed 's/^[[:space:]]*run[[:space:]]*//' <<< "$line" | sed 's/[[:space:]]*#.*//')
      echo "Running: $cmd"
      eval "$cmd"
      ;;
    *)
      echo "Warning: unknown keyword '$keyword' — skipping" >&2
      ;;
  esac
done < "$SETUPFILE"

# Close the plugins=() block and source Oh My Zsh
echo ")" >> "$ZSH_PLUGINS_FILE"
echo 'autoload -Uz compinit && compinit' >> "$ZSH_PLUGINS_FILE"
echo 'source "${ZSH:-$HOME/.oh-my-zsh}/oh-my-zsh.sh"' >> "$ZSH_PLUGINS_FILE"

echo ""
echo "Done. Run 'source ~/.zshrc' to reload your shell."
