name: Build CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build_ci:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup
        run: |
          make setup
      
      - name: Configure
        run: |
          make configure

      - name: Install dev apps
        run: |
          make install-dev
          make install-dev-ios
      
      - name: Install design apps
        run: |
          make install-design
      
      - name: Install utility apps
        run: | 
          make install-productivity
          make install-teamwork

      - name: Install fun apps
        run: |
          make install-fun
